apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  config.xml: |
    <yandex>
      <storage_configuration>
        <disks>
          <default>
            <path>/var/lib/clickhouse</path>
          </default>
          <cold_disk>
            <path>/mnt/cold_storage</path>
          </cold_disk>
        </disks>
        <policies>
          <hot_cold_policy>
            <volumes>
              <hot>
                <disk>default</disk>
              </hot>
              <cold>
                <disk>cold_disk</disk>
              </cold>
            </volumes>
            <move_factor>0.2</move_factor>
          </hot_cold_policy>
        </policies>
      </storage_configuration>
    </yandex>
