apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: client
          volumeMounts:
            - name: hot-storage
              mountPath: /var/lib/clickhouse
            - name: cold-storage
              mountPath: /mnt/cold_storage
            - name: clickhouse-config-volume
              mountPath: /etc/clickhouse-server/config.xml
              subPath: config.xml
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
  volumeClaimTemplates:
    - metadata:
        name: hot-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.storage.hot.class }}"
        resources:
          requests:
            storage: "{{ .Values.storage.hot.size }}"
    - metadata:
        name: cold-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.storage.cold.class }}"
        resources:
          requests:
            storage: "{{ .Values.storage.cold.size }}"
  volumes:
    - name: clickhouse-config-volume
      configMap:
        name: clickhouse-config
